Fixed classpath layout of tools “distribution”
Unfortunately, the transitive dependencies do not all have unique
artifact IDs. Example:
io.github.microutils:kotlin-logging:1.5.4 depends on
io.github.microutils.kotlin-logging:kotlin-logging:1.5.4

Prior to this commit, launching the command line tool from the
issue-tracking-tool/target/distribution directory would sometimes result
in a java.lang.NoClassDefFoundError.